# Generated by Django 4.0.10 on 2023-06-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=230)),
                ('subtitle', models.CharField(max_length=240)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13)),
            ],
        ),
    ]
